### ISSUE TITLE
color changing candles adaptation

### ISSUE THREAD

**Issue by rzv-trsc** [3ative/Smart-Candles#2]
Great work, thanks for the shared video & code! 

I have in mind a similar project I'd like to kindly ask for your help on:

I have a set of color changing candles quite similar to [these](https://www.therange.co.uk/lighting/led-lighting/novelty-led-lighting/colour-changing-led-candles/#139321). Memory resemblance, will fact-check the exact model/specs if interested. D1 mini / esp32 boards available also. 

Haven't tinkered around with them (since I'm not not an experienced coder/tinkerer) but I'm guessing my candles are using rgb led's (3 candles x 3 inputs + ground each) - probably gonna crack open one of them in the weekend to confirm.

Is there any chance you might be willing to take a look and help with the coding required?

I'm thinking, besides using them for mood lightning, they could also work as an indicator for color-coded alerts (i. e. Internet shortages etc).

Sorry if I'm asking for too much.

**Comment by 3ative** [comment]
Lemme know what you find inside once you take one apart.

**Comment by rzv-trsc** [comment]
Lemme start by thanking you for the unexpectedly quick response. 

quick update: 

<a href="https://ibb.co/zVspcD1"><img src="https://i.ibb.co/zVspcD1/board-led-transistor.jpg" alt="board-led-transistor" border="0"></a> <a href="https://ibb.co/pKT5tFg"><img src="https://i.ibb.co/pKT5tFg/board-circuitry-different-view.jpg" alt="board-circuitry-different-view" border="0"></a> <a href="https://ibb.co/hFk72fc"><img src="https://i.ibb.co/hFk72fc/full-circuitry.jpg" alt="full-circuitry" border="0"></a> <a href="https://ibb.co/0YtLFPQ"><img src="https://i.ibb.co/0YtLFPQ/20220119-164706.jpg" alt="20220119-164706" border="0"></a>

<a href="https://ibb.co/ZBb8wQm"><img src="https://i.ibb.co/ZBb8wQm/magnigying-glass.jpg" alt="magnigying-glass" border="0"></a> <a href="https://ibb.co/vdcBd3g"><img src="https://i.ibb.co/vdcBd3g/20220119-172631.jpg" alt="20220119-172631" border="0"></a>

dismantled all 3 candles i've got, to better expose the circuitry inside. 
- powered by 2AA batteries via an on/off switch (checked voltage, 2.3V where white&yellow lines are soldered to the tiny board)
- candles are operated via IR remote (on/off/timer/color from pre-existing buttons on the remote)
- LED is hooked up to the tiny green board BUT only has 3 leads and it's tightly glued at the far end (cannot better expose LED/board/tiny black thingy* unless if cutting the leads)

(*) tiny black thingy is, i'm guessing, the IR receiver (I'm not seeing any markings on it). Second row pics: in just one of the 3 candles, the layout is different (and exposes the black thingy). 

any thoughts about this? do you reckon it's doable? 
i'm also thinking about hooking an IR blaster to a d1 mini and using it to smart-control the candles, but this is a one way communication (cannot smart-check/read the status of the candles). 

Many, many thanks for sharing your time with me!

**Comment by 3ative** [comment]
No worries fella...

Hmmm, only 3 legs on that LED. Not an RGB LED then, that would need 4 - I guess it's digital then. In which case it'll have +Volts, 0Volts and Data. 
I don't think it's a WS28xx as every one I've seen needs 5 Volts - But, I could be wrong. 

Is there noting else on that green PCB, anything like a 'Blob' chip...
E.G.
![image](https://user-images.githubusercontent.com/51385971/150177468-6f09e59e-c175-4e2c-ad23-3b310b35c1ea.png)

**Comment by rzv-trsc** [comment]
most definitely no blob :-) : 
<a href="https://ibb.co/2nb8jgN"><img src="https://i.ibb.co/2nb8jgN/20220119-190225.jpg" alt="20220119-190225" border="0"></a> <a href="https://ibb.co/1Q1y4zL"><img src="https://i.ibb.co/1Q1y4zL/20220119-190207.jpg" alt="20220119-190207" border="0"></a>

one side has the printout and the other is plain blank / unfinished; thank god for the second candle with the board in errect position :-)

**Comment by rzv-trsc** [comment]
also, not sure if this helps: colors aren't the greatest. 
the blue is very faded (according to the remote presets, these should be B, R, G colors 
(warm white light in the background, photos taken seconds apart, same lightning conditions)

<a href="https://ibb.co/Nrkg14N"><img src="https://i.ibb.co/Nrkg14N/20220119-191424.jpg" alt="20220119-191424" border="0"></a> <a href="https://ibb.co/km91FcT"><img src="https://i.ibb.co/km91FcT/20220119-191417.jpg" alt="20220119-191417" border="0"></a> <a href="https://ibb.co/mhC3ssj"><img src="https://i.ibb.co/mhC3ssj/20220119-191420.jpg" alt="20220119-191420" border="0"></a>

ps. that's how faded the blue is - it's not the reflection of the computer screen :-)

**Comment by 3ative** [comment]
Hmmm.... Well, it looks like all the processing and colour changes is being done on or in the LED casing....

My best advice would be to ditch it and put in a WS2812 'Pixel' in it's place.

**Comment by rzv-trsc** [comment]
Thanks for looking into it, then. 

Kinda besides the purpose of your programming, but any chance to help with some coding, if not asking too much? That'd mean using each candle as an indicator (each having it's own d1-mini). 

i'm thinking of using the candles to conceal the smart stuff, and using d1 mini plus an LED. 
I do have a spare [color RGB LED](https://www.optimusdigital.ro/ro/optoelectronice-led-uri/484-led-rgb-anod-comun.html?search_query=led&results=824), or i might order some [WS2812](https://www.emag.ro/modul-cu-1-led-rgb-5050-ws2812-ai1021/pd/DVCZBXMBM/?X-Search-Id=4d035c44dd1db8bc47b2&X-Product-Id=82682008&X-Search-Page=1&X-Search-Position=3&X-Section=search&X-MB=0&X-Search-Action=view) as suggested. Tend to prefer the first one as I already have what's needed, plus local ws2812 are hard to find, and the type in the link above might not properly lit the candle. . :-) 

(sorry, links are to local shops, but one image is woth 1000 words, right?)

**Comment by 3ative** [comment]
I'd be happy to answer specific questions but, I do have the time to help with your full coding.... soz.

Yeah, you could use the LEDs you have - It's always better to use what's at hand. I only suggested WS2812 for ease of the build, but the coding would have been more complicated. 😉

**Comment by rzv-trsc** [comment]
Indeed. Time is scarce for us all.
Many thanks for all your time and effort!

**Comment by 3ative** [comment]
You are welcome. 
I hope you manage to get something done.
